from sklearn.metrics import mean_absolute_error, mean_squared_error

from machine_learning_solver.PINN import BurgersPINN
from numerical_solvers.Burgers_Upwind import BurgersUpwind
from util.generate_plots import *
import numpy as np

# Part 1: Build and train PINN
pinn = BurgersPINN()
pinn.generate_training_data(n_initial=50, n_boundary=25, equidistant=False)
pinn.perform_training(max_n_epochs=3000, track_losses=True, batch_size='full')

# Part 2: Use initial data generated by PINN and use them as IC for Upwind solver

# Generate initial data for Upwind solver
n_spatial = 1281
n_temporal = 10**4 + 1
feat = np.column_stack((np.linspace(-1, 1, n_spatial), np.zeros(n_spatial)))
initial_data = pinn.network(feat)[:, 0]

# Run solver
upwind = BurgersUpwind(n_spatial=n_spatial, n_temporal=n_temporal, u0=initial_data, order=2)
upwind.time_integrate()

# Plot both solutions
generate_two_contour_and_snapshots_plots(u1=pinn.u_pred, u2=upwind.u_numerical)
# generate_two_contour_and_snapshots_plots(u1=pinn.u_pred, u2=upwind.u_numerical, train_feat=pinn.train_feat,
#                                          savefig_path=f'scripts/Burgers/4.2.2_run_Upwind_with_PINN/'
#                                                       f'Fig7_PINN_and_Upwind.jpg')

# Compute l2 error between Upwind and PINN solution
x = np.linspace(-1, 1, n_spatial)
t = np.linspace(0, 1, n_temporal)
x_mesh, t_mesh = np.meshgrid(x, t)
eval_feat = np.hstack((x_mesh.flatten()[:, None], t_mesh.flatten()[:, None]))
pinn_u_pred = np.reshape(pinn.network(eval_feat), (n_temporal, n_spatial)).T
print(f"L2(Upwind - PINN): {np.sqrt(mean_squared_error(pinn_u_pred, upwind.u_numerical))}")
